# Generated by Django 3.2.6 on 2021-08-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20210827_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='pms.projectstatus', to_field='level_tag'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='level_tag',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
