# Generated by Django 3.2.6 on 2021-08-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20210827_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
