# Generated by Django 3.2.6 on 2021-08-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20210827_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='all_status',
            field=models.ManyToManyField(blank=True, null=True, to='pms.ProjectLevel'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='pms.projectlevel'),
        ),
    ]
